[package]
name = "composable-admin"
version = "0.1.0"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]
edition = "2018"

[[example]]
name = "contract"
crate-type = ["staticlib"]
test = true

[dependencies]
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.4-debug-print" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

require-admin = { path = "../require-admin", optional = true }
fadroma-scrt-storage = { path = "../../storage" }

[features]
default = ["derive"]
derive = ["require-admin"]
