[package]
name    = "fadroma-proc-auth"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0"
description = "Require admin macro for Fadroma"
repository = "https://github.com/hackbg/fadroma"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
