[package]
name    = "fadroma"
version = "100.0.0"
edition = "2018"
license = "AGPL-3.0"
authors = [

  # Core maintainers:
  "Adam A. <adam@hack.bg>",
  "Asparuh Kamenov <aakamenov@hack.bg>",
  "denismaxim0v <denis_maxim0v@protonmail.com>",

  # Featuring contributions by:
  "Chris Ricketts <chris.ricketts@steribar.com>",
  "Tibor Hudik <tibor@barrage.net>",
  "Wiz1991 <wizoftime92@gmail.com>",
  "hydropump3 <3ki2fiay@anonaddy.me>",

  # SNIP-20 implementation based on:
  "Itzik <itzik@keytango.io>"

]

[lib]
path = "lib.rs"

[features]
default = [
  # Features
  "scrt", "message", "response"
]

scrt = [
  # Dependencies
  "fadroma-platform-scrt"
]

admin = [
  # Features
  "scrt", "derive", "storage",
  # Dependencies
  "fadroma-proc-auth", "serde"
]

permit = [
  # Features
  "scrt",
  # Dependencies
  "ripemd160", "secp256k1", "sha2", "remain",
]

vk = [
  # Features
  "scrt", "derive", "storage",
  # Dependencies
  "fadroma-proc-auth", "serde", "rand_chacha", "rand_core", "subtle"
]

composability = [
  # Features
  "scrt", "storage",
  # Dependencies
  "serde"
]

derive = [
  # Dependencies
  "fadroma-proc-derive"
]

ensemble = [
  # Features
  "scrt", "storage",
  # Dependencies
  "oorandom"
]

killswitch = [
  # Features
  "scrt", "admin", "storage", "derive",
  # Dependencies
  "serde"
]

math = [
  # Features
  "scrt",
  # Dependencies
  "serde", "primitive-types", "rand_core", "rand_chacha", "subtle", "sha2"
]

snip20-client = [
  # Features
  "scrt",
  # Dependencies
  "secret-toolkit"
]

snip20-impl = [
  # Features
  "scrt", "admin", "permit", "vk",
  # Dependencies
  "secret-toolkit", "storage", "serde", "schemars", "bincode2"
]

storage = [
  "scrt",
  # Dependencies
  "serde"
]

message = [
  # Dependencies
  "fadroma-proc-message"
]

response = [
  # Features
  "scrt"
]

# Misc

reexport-secret-toolkit = [ "secret-toolkit" ]

# Old
backtraces = [] # TODO set backtraces on components
browser    = [ "backtraces" ]
harness    = []

[dependencies]
# Supported platforms
fadroma-platform-scrt = { optional = true, path = "../fadroma-platform-scrt" }

# Procedural macro crates
fadroma-derive-canonize = { path = "../fadroma-derive-canonize" }
fadroma-proc-auth     = { optional = true, path = "../fadroma-proc-auth" }
fadroma-proc-derive   = { optional = true, path = "../fadroma-proc-derive" }
fadroma-proc-message  = { optional = true, path = "../fadroma-proc-message" }

# Dependencies
bincode2        = { optional = true, version = "2.0.1"  }
oorandom        = { optional = true, version = "11.1.3" }
primitive-types = { optional = true, version = "0.9.1",   default-features = false }
rand_chacha     = { optional = true, version = "0.2.2",   default-features = false }
rand_core       = { optional = true, version = "0.5.1",   default-features = false }
remain          = { optional = true, version = "0.2.2"  }
schemars        = { optional = true, version = "0.7"    }
ripemd160       = { optional = true, version = "0.9.1"  }
secp256k1       = { optional = true, version = "0.20.3" }
secret-toolkit  = { optional = true, version = "0.3.0",   default-features = false, features = ["snip20", "snip721", "storage"] }
serde           = { optional = true, version = "1.0.103", default-features = false, features = ["derive"] }
sha2            = { optional = true, version = "0.9.1",   default-features = false }
subtle          = { optional = true, version = "2.4.0",   default-features = false }

# Enable iterator for testing (not supported in production)
[target.'cfg(not(target_arch="wasm32"))'.dependencies]
fadroma-platform-scrt = { optional = true, path = "../fadroma-platform-scrt", features = ["iterator"] }
