[package]
name    = "fadroma-scrt-storage"
version = "0.1.0"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]
edition = "2018"

[lib]
name = "fadroma_scrt_storage"
path = "lib.rs"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

fadroma-scrt-base = { path = "../base" }
