name: Publish documentation
on: [push]
jobs:
  site:
    name: build website
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with: { submodules: "recursive" }

      - name: Determine default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Get Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - run: cp _Cargo.toml Cargo.toml

      - name: Generate Rust documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

      - name: Install PNPM and deps
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Generate JS documentation
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192 pnpm document

      - name: Render homepage
        run: |
          pnpm render

      - name: Publish
        if:   github.ref == env.default_branch_ref
        run: |
          ls
          rm .gitignore
          mkdir .docs
          cp -rv ./target/doc .docs/rs
          cp -rv ./docs .docs/js
          cp -rv ./doc/* .docs/
          tar -cvf .docs/nix shell.nix
          echo "fadroma.tech" > .docs/CNAME
          ls -al .docs
          git add -f .docs
          git config --global user.email "hello@hack.bg"
          git config --global user.name "hack.bg"
          git commit -m "ðŸ¤– built docs @ $(date -u)"
          git subtree split --branch gh-pages --prefix .docs
          git push --force origin gh-pages
